Resources:
  CurrentTempFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/current_temp.zip
      FunctionName: currentTemp
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/currentTemp'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt CurrentTempRole.Arn
      Runtime: 'ruby3.3'
  CurrentTempEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt InboxTable.StreamArn
      FilterCriteria:
        Filters:
          - Pattern: '{ "eventName": ["INSERT"], "dynamodb": { "NewImage": { "message_body": { "S": ["Current", "current", "temp", "Temp", "currenttemp", "Currenttemp"] } } } }'  
      FunctionName: !Ref CurrentTempFunction
      MaximumBatchingWindowInSeconds: 3
      ParallelizationFactor: 1
      StartingPosition: LATEST