Resources:
  EmailProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/email_processor.zip
      FunctionName: emailProcessor
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/emailProcessor'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt EmailProcessorRole.Arn
      Runtime: 'ruby3.3'
  EmailProcessorEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt OutboxTable.StreamArn
      FilterCriteria:
        Filters:
          - Pattern: '{ "eventName": ["INSERT"], "dynamodb": { "NewImage": { "message_body": { "S": ["Current", "current", "temp", "Temp", "currenttemp", "Currenttemp"] } } } }'  
      FunctionName: !Ref CurrentTempFunction
      MaximumBatchingWindowInSeconds: 3
      ParallelizationFactor: 1
      StartingPosition: LATEST