Resources:
  HeartbeatMonitorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/heartbeat_monitor.zip
      Environment:
        Variables:
          DEVICE_ID: 1d003c000947363339343638
      FunctionName: heartbeatMonitor
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/heartbeatMonitor'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt HeartbeatMonitorRole.Arn
      Runtime: 'ruby3.3'