Resources:
  SendEmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/send_email.zip
      FunctionName: sendEmail
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/sendEmail'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt SendEmailRole.Arn
      Runtime: 'ruby3.3'