Resources:
  SendSMSFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/send_sms.zip
      Environment:
        Variables:
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
      FunctionName: sendSMS
      Layers:
        - !Ref TwilioClientLayer
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/sendSMS'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt SendSMSRole.Arn
      Runtime: 'ruby3.3'