Resources:
  SMSProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/sms_processor.zip
      FunctionName: smsProcessor
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/smsProcessor'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt SMSProcessorRole.Arn
      Runtime: 'ruby3.3'