Resources:
  TempMonitorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: tcochran317-lambda
        S3Key: functions/temp_monitor.zip
      Environment:
        Variables:
          ALERT_TEMP: -5
          DEVICE_ID: !Ref DeviceId
      FunctionName: tempMonitor
      LoggingConfig:
        LogFormat: Text
        LogGroup: '/aws/lambda/tempMonitor'
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt TempMonitorRole.Arn
      Runtime: 'ruby3.3'