Resources:
  TwilioClientLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - ruby2.7
        - ruby3.3
      Content:
           S3Bucket: tcochran317-lambda
           S3Key: layers/twilio.zip
      Description: 'Twilio client gem'
      LayerName: 'Twilio'