Resources:
  InboxTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: message_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      DeletionProtectionEnabled: false
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: message_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
      StreamSpecification:
        StreamEnabled: true
        StreamViewType: NEW_AND_OLD_IMAGES
      TableClassSummary:
        TableClass: STANDARD
      TableName: inbox
Outputs:
  InboxTableARN:
    Description: "ARN for temp_data table"
    Value: !GetAtt InboxTable.Arn