Resources:
  OutboxTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: created_at
        AttributeType: S
      - AttributeName: message_id
        AttributeType: S
      DeletionProtectionEnabled: false
      KeySchema:
      - AttributeName: message_id
        KeyType: HASH
      - AttributeName: created_at
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamEnabled: true
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: outbox
Outputs:
  OutboxTableARN:
    Description: "ARN for outbox table"
    Value: !GetAtt OutboxTable.Arn