Resources:
  TempDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: device_id
        AttributeType: S
      - AttributeName: published_at
        AttributeType: S
      DeletionProtectionEnabled: false
      KeySchema:
      - AttributeName: device_id
        KeyType: HASH
      - AttributeName: published_at
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: temp_data
Outputs:
  TempDataTableARN:
    Description: "ARN for temp_data table"
    Value: !GetAtt TempDataTable.Arn