Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: active
        AttributeType: S
      - AttributeName: heartbeatAlert
        AttributeType: S
      - AttributeName: tempAlert
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      DeletionProtectionEnabled: false
      GlobalSecondaryIndexes:
        - 
          IndexName: tempAlert-index
          IndexSizeBytes: 87
          IndexStatus: ACTIVE
          ItemCount: 2
          KeySchema:
          - AttributeName: tempAlert
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            NumberOfDecreasesToday: 0
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - 
          IndexName: active-index
          IndexSizeBytes: 87
          IndexStatus: ACTIVE
          ItemCount: 2
          KeySchema:
          - AttributeName: active
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            NumberOfDecreasesToday: 0
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - 
          IndexName: heartbeatAlert-index
          IndexSizeBytes: 51
          IndexStatus: ACTIVE
          ItemCount: 1
          KeySchema:
          - AttributeName: heartbeatAlert
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            NumberOfDecreasesToday: 0
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: users
