Resources:
  DynamoDBInboxPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DynamoDB-inbox 
      - PolicyDocument: 
          Version: 2012-10-17,
          Statement:
            - Effect: Allow,
              Action:
                - "dynamodb:ListContributorInsights"
                - "dynamodb:DescribeReservedCapacityOfferings"
                - "dynamodb:ListGlobalTables"
                - "dynamodb:ListTables"
                - "dynamodb:DescribeReservedCapacity"
                - "dynamodb:ListBackups"
                - "dynamodb:PurchaseReservedCapacityOfferings"
                - "dynamodb:ListImports"
                - "dynamodb:DescribeLimits"
                - "dynamodb:DescribeEndpoints"
                - "dynamodb:ListExports"
                - "dynamodb:ListStreams"
              Resource: 
                - "*"
            - Effect: Allow,
              Action: 
                - "dynamodb:*"
              Resource: 
                - !GetAtt InboxTable.Arn
                - !GetAtt InboxTable.StreamArn
                - !Sub
                  - "${Arn}/index/*"
                  - Arn: !!Ref InboxTable
      Roles:
        - !Ref CurrentTempRole
        - !Ref EmailProcessorRole
        - !Ref SMSProcessorRole